config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  root to: "images#index"
  resources :images, only: [:index, :new, :create, :show, :destroy] do
   collection do
     get 'search'
     get 'notice'
   end
  end
  resources :users, only: [:new, :show, :index]
  get '/ordering' => 'users#ordering'
  resources :carts, only:[:show, :destroy]
  post '/add_item' => 'carts#add_item'
  resources :line_items, only: :destroy
  resources :calendars, only: [:new, :create, :show] do
    member do 
      get'show_order'
    end
    resources :orders, only: [:new, :create]
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items,dependent: :destroy
  has_many :images, through: :line_items
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_line_item, only: [:add_item, :destroy, :delete_item]
  before_action :set_user
  before_action :set_cart

  def show
    @line_items = @cart.line_items
  end

  def add_item
    @line_item = @cart.line_items.build(image_id: params[:image_id])if @line_item.blank?
    if @line_item.save
      redirect_to current_cart
    else
      redirect_to controller: "images#show"
    end
  end

  def destroy
    @cart.destroy
    redirect_to root_path
  end

  private
  def set_user
    @user = current_user
  end

  def set_line_item
    @line_item = current_cart.line_items.find_by(image_id: params[:image_id])
  end
  
  def set_cart
    @cart = current_cart
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<div class="main">
  <p class="cart-title">＜カートのなか＞</p>
  <div class="cart-pictures">
    <% @line_items.each do |line_item|%>
      <div class="select-image">
        <div class="picture-box">
          <%= image_tag line_item.image.picture, class:"cart-image-picture" %>
        </div>
        <div class="image-data">
          <div class="top-data">
            <div class="image-user">
              <%= image_tag line_item.image.user.icon, class:"usericon" %>
              <%= line_item.image.user.nickname %>
            </div>
            <div>
              <%= "シーズン：#{line_item.image.season.name}"%>
            </div>
          </div>
          <div class="bottom-data">
            <div>
              <%if line_item.image.tags.present?%>
                <% line_item.image.tags.each do |tag|%>
                  <%= "##{tag.name}" %>
                <% end%>
              <% end %>
            </div>
            <div class="delete-btn">
              <%= link_to "削除", line_item_path(line_item.id), method: :delete, class:"imagecal-link" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="cart-menu">
    <div class="cart-bottom-menu">
      <div class="cart-menu-box">
        <div class="imagecal-btn">
          <%= link_to "トップに戻る", root_path, class:"imagecal-link" %>
        </div>
        <div class="imagecal-btn">
          <%= link_to "カートを空にする", cart_path(@current_cart.id), method: :delete, class:"imagecal-link" %>
        </div>
        <% if @current_cart.images.length == 12%>
          <div class="imagecal-btn">
            <%= link_to "プレビューページ", new_calendar_path, class:"imagecal-link" %>
          </div>
        <% end %>
      </div>
      <div class="images-count">
        <%= "合計：　#{@current_cart.images.length}個" %>
      </div>
    </div>
  <div>
</div>