config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  root to: "images#index"
  resources :images, only: [:index, :new, :create, :show, :destroy] do
   collection do
     get 'search'
     get 'notice'
   end
  end
  resources :users, only: [:new, :show, :index]
  get '/ordering' => 'users#ordering'
  resources :carts, only:[:show, :destroy]
  post '/add_item' => 'carts#add_item'
  resources :line_items, only: :destroy
  resources :calendars, only: [:new, :create, :show] do
    member do 
      get'show_order'
    end
    resources :orders, only: [:new, :create]
  end
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  has_many :image_calendars
  has_many :images, through: :image_calendars
  has_one :order
  has_many :image_month

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :month1
  belongs_to :month2
  belongs_to :month3
  belongs_to :month4
  belongs_to :month5
  belongs_to :month6
  belongs_to :month7
  belongs_to :month8
  belongs_to :month9
  belongs_to :month10
  belongs_to :month11
  belongs_to :month12

  validates :month1_id, numericality: {other_than:1, message:"を選択してください(Picture1)"}
  validates :month2_id, numericality: {other_than:1, message:"を選択してください(Picture2)"}
  validates :month3_id, numericality: {other_than:1, message:"を選択してください(Picture3)"}
  validates :month4_id, numericality: {other_than:1, message:"を選択してください(Picture4)"}
  validates :month5_id, numericality: {other_than:1, message:"を選択してください(Picture5)"}
  validates :month6_id, numericality: {other_than:1, message:"を選択してください(Picture6)"}
  validates :month7_id, numericality: {other_than:1, message:"を選択してください(Picture7)"}
  validates :month8_id, numericality: {other_than:1, message:"を選択してください(Picture8)"}
  validates :month9_id, numericality: {other_than:1, message:"を選択してください(Picture9)"}
  validates :month10_id, numericality: {other_than:1, message:"を選択してください(Picture10)"}
  validates :month11_id, numericality: {other_than:1, message:"を選択してください(Picture11)"}
  validates :month12_id, numericality: {other_than:1, message:"を選択してください(Picture12)"}


  with_options presence: true do
    validates :img1
    validates :img2
    validates :img3
    validates :img4
    validates :img5
    validates :img6
    validates :img7
    validates :img8
    validates :img9
    validates :img10
    validates :img11
    validates :img12
  end


end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :authenticate_user!

  def new
    @images = current_cart.images
    @calendar = Calendar.new
  end

  def create
    @images = current_cart.images
    @calendar = Calendar.new(calendar_params)
    if @calendar.valid?
      @calendar.save
      ImageCalendar.save(@calendar, @images)
      ImageMonth.save(@calendar)
      redirect_to calendar_path(@calendar.id)
    else
      flash[:notice] = "選択漏れがあります！下の表を確認してください！"
      redirect_to new_calendar_path
    end
  end

  def show
    @calendar = Calendar.find(params[:id])
    @image_months = @calendar.image_month.all.order("month ASC")
    @image_month1 = @image_months[0]
    @image_month2 = @image_months[1]
    @image_month3 = @image_months[2]
    @image_month4 = @image_months[3]
    @image_month5 = @image_months[4]
    @image_month6 = @image_months[5]
    @image_month7 = @image_months[6]
    @image_month8 = @image_months[7]
    @image_month9 = @image_months[8]
    @image_month10 = @image_months[9]
    @image_month11 = @image_months[10]
    @image_month12 = @image_months[11]
    @images = @calendar.images
  end

  def show_order
    @order = Order.find(params[:id])
    @image_months = @order.calendar.image_month.all.order("month ASC")
    @image_month1 = @image_months[0]
    @image_month2 = @image_months[1]
    @image_month3 = @image_months[2]
    @image_month4 = @image_months[3]
    @image_month5 = @image_months[4]
    @image_month6 = @image_months[5]
    @image_month7 = @image_months[6]
    @image_month8 = @image_months[7]
    @image_month9 = @image_months[8]
    @image_month10 = @image_months[9]
    @image_month11 = @image_months[10]
    @image_month12 = @image_months[11]
    @images = @order.calendar.images

  end

  private
  def calendar_params
    params.require(:calendar).permit(
      :month1_id, :img1, :month2_id, :img2, :month3_id, :img3, :month4_id, :img4,
      :month5_id, :img5, :month6_id, :img6, :month7_id, :img7, :month8_id, :img8,
      :month9_id, :img9, :month10_id, :img10, :month11_id, :img11, :month12_id, :img12
    )
  end
end

app/views/calendars/_calendar.html.erb
<div class="preview">
  <% @images.each do |image| %>
    <% if image.id == @image_month1.img %>
      <div class="preview-calendar">
        <div class="preview-picture">
          <%= image_tag image.picture, class:"preview-picture-box" %>
        </div>
        <div class="schedule">
          <%= image_tag 'jan.png', class:"preview-schedule" %>
        </div>
      </div>
    <% end %>
  <% end %>
  <% @images.each do |image| %>
    <% if image.id == @image_month2.img %>
      <div class="preview-calendar">
        <div class="preview-picture">
          <%= image_tag image.picture, class:"preview-picture-box" %>
        </div>
        <div class="schedule">
          <%= image_tag 'feb.png', class:"preview-schedule" %>
        </div>
      </div>
    <% end %>
  <% end %>
  <% @images.each do |image| %>
    <% if image.id == @image_month3.img %>
      <div class="preview-calendar">
        <div class="preview-picture">
          <%= image_tag image.picture, class:"preview-picture-box" %>
        </div>
        <div class="schedule">
          <%= image_tag 'mar.png', class:"preview-schedule" %>
        </div>
      </div>
    <% end %>
  <% end %>
  <% @images.each do |image| %>
    <% if image.id == @image_month4.img %>
      <div class="preview-calendar">
        <div class="preview-picture">
          <%= image_tag image.picture, class:"preview-picture-box" %>
        </div>
        <div class="schedule">
          <%= image_tag 'apr.png', class:"preview-schedule" %>
        </div>
      </div>
    <% end %>
  <% end %>
  <% @images.each do |image| %>
    <% if image.id == @image_month5.img %>
      <div class="preview-calendar">
        <div class="preview-picture">
          <%= image_tag image.picture, class:"preview-picture-box" %>
        </div>
        <div class="schedule">
          <%= image_tag 'may.png', class:"preview-schedule" %>
        </div>
      </div>
    <% end %>
  <% end %>
  <% @images.each do |image| %>
    <% if image.id == @image_month6.img %>
      <div class="preview-calendar">
        <div class="preview-picture">
          <%= image_tag image.picture, class:"preview-picture-box" %>
        </div>
        <div class="schedule">
          <%= image_tag 'jun.png', class:"preview-schedule" %>
        </div>
      </div>
    <% end %>
  <% end %>
  <% @images.each do |image| %>
    <% if image.id == @image_month7.img %>
      <div class="preview-calendar">
        <div class="preview-picture">
          <%= image_tag image.picture, class:"preview-picture-box" %>
        </div>
        <div class="schedule">
          <%= image_tag 'jul.png', class:"preview-schedule" %>
        </div>
      </div>
    <% end %>
  <% end %>
  <% @images.each do |image| %>
    <% if image.id == @image_month8.img %>
      <div class="preview-calendar">
        <div class="preview-picture">
          <%= image_tag image.picture, class:"preview-picture-box" %>
        </div>
        <div class="schedule">
          <%= image_tag 'aug.png', class:"preview-schedule" %>
        </div>
      </div>
    <% end %>
  <% end %>
  <% @images.each do |image| %>
    <% if image.id == @image_month9.img %>
      <div class="preview-calendar">
        <div class="preview-picture">
          <%= image_tag image.picture, class:"preview-picture-box" %>
        </div>
        <div class="schedule">
          <%= image_tag 'sep.png', class:"preview-schedule" %>
        </div>
      </div>
    <% end %>
  <% end %>
  <% @images.each do |image| %>
    <% if image.id == @image_month10.img %>
      <div class="preview-calendar">
        <div class="preview-picture">
          <%= image_tag image.picture, class:"preview-picture-box" %>
        </div>
        <div class="schedule">
          <%= image_tag 'oct.png', class:"preview-schedule" %>
        </div>
      </div>
    <% end %>
  <% end %>
  <% @images.each do |image| %>
    <% if image.id == @image_month11.img %>
      <div class="preview-calendar">
        <div class="preview-picture">
          <%= image_tag image.picture, class:"preview-picture-box" %>
        </div>
        <div class="schedule">
          <%= image_tag 'nov.png', class:"preview-schedule" %>
        </div>
      </div>
    <% end %>
  <% end %>
  <% @images.each do |image| %>
    <% if image.id == @image_month12.img %>
      <div class="preview-calendar">
        <div class="preview-picture">
          <%= image_tag image.picture, class:"preview-picture-box" %>
        </div>
        <div class="schedule">
          <%= image_tag 'dec.png', class:"preview-schedule" %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/calendars/_monthselect.html.erb
<div class="month-select-form">
  <%= form_with model: @calendar, url: calendars_path, id:"form-box",  local: true do |f|%>
    <div class="month-select">
      <div class="pict">
        <%= f.label :month1_id, "PICTURE1",class:"month-label" %>
        <%= f.hidden_field :img1, value:@images[0].id %>
        <%= f.collection_select(:month1_id, Month1.all, :id, :name, {}, {class:"month_select_box", id:"select1"}) %>
      </div>
      <div class="pict">
        <%= f.label :month2_id, "PICTURE2",class:"month-label" %>
        <%= f.hidden_field :img2, value:@images[1].id %>
        <%= f.collection_select(:month2_id, Month2.all, :id, :name, {}, {class:"month_select_box", id:"select2"}) %>
      </div>
      <div class="pict">
        <%= f.label :month3_id, "PICTURE3",class:"month-label" %>
        <%= f.hidden_field :img3, value:@images[2].id %>
        <%= f.collection_select(:month3_id, Month3.all, :id, :name, {}, {class:"month_select_box", id:"select3"}) %>
      </div>
      <div class="pict">
        <%= f.label :month4_id, "PICTURE4",class:"month-label" %>
        <%= f.hidden_field :img4, value:@images[3].id %>
        <%= f.collection_select(:month4_id, Month4.all, :id, :name, {}, {class:"month_select_box", id:"select4"}) %>
      </div>
      <div class="pict">
        <%= f.label :month5_id, "PICTURE5",class:"month-label" %>
        <%= f.hidden_field :img5, value:@images[4].id %>
        <%= f.collection_select(:month5_id, Month5.all, :id, :name, {}, {class:"month_select_box", id:"select5"}) %>
      </div>
      <div class="pict">
        <%= f.label :month6_id, "PICTURE6",class:"month-label" %>
        <%= f.hidden_field :img6, value:@images[5].id %>
        <%= f.collection_select(:month6_id, Month6.all, :id, :name, {}, {class:"month_select_box", id:"select6"}) %>
      </div>
      <div class="pict">
        <%= f.label :month7_id, "PICTURE7",class:"month-label" %>
        <%= f.hidden_field :img7, value:@images[6].id %>
        <%= f.collection_select(:month7_id, Month7.all, :id, :name, {}, {class:"month_select_box", id:"select7"}) %>
      </div>
      <div class="pict">
        <%= f.label :month8_id, "PICTURE8",class:"month-label" %>
        <%= f.hidden_field :img8, value:@images[7].id %>
        <%= f.collection_select(:month8_id, Month8.all, :id, :name, {}, {class:"month_select_box", id:"select8"}) %>
      </div>
      <div class="pict">
        <%= f.label :month9_id, "PICTURE9",class:"month-label" %>
        <%= f.hidden_field :img9, value:@images[8].id %>
        <%= f.collection_select(:month9_id, Month9.all, :id, :name, {}, {class:"month_select_box", id:"select9"}) %>
      </div>
      <div class="pict">
        <%= f.label :month10_id, "PICTURE10",class:"month-label" %>
        <%= f.hidden_field :img10, value:@images[9].id %>
        <%= f.collection_select(:month10_id, Month10.all, :id, :name, {}, {class:"month_select_box", id:"select10"}) %>
      </div>
      <div class="pict">
        <%= f.label :month11_id, "PICTURE11",class:"month-label" %>
        <%= f.hidden_field :img11, value:@images[10].id %>
        <%= f.collection_select(:month11_id, Month11.all, :id, :name, {}, {class:"month_select_box", id:"select11"}) %>
      </div>
      <div class="pict">
        <%= f.label :month12_id, "PICTURE12",class:"month-label" %>
        <%= f.hidden_field :img12, value:@images[11].id %>
        <%= f.collection_select(:month12_id, Month12.all, :id, :name, {}, {class:"month_select_box", id:"select12"}) %>
      </div>
    </div>
    <%= render partial:"selected" %>
    <div class="send-btn-box">
      <%= f.submit "SEND", class:"send-btn" %>
    </div>
  <% end %>
</div>

app/views/calendars/_selected.html.erb
<div class="selected-month", id="selected-month">
  <div class="picture-selected", id="picture1-select">
    <p>picture1:　</p>
  </div>
  <div class="picture-selected", id="picture2-select">
    <p>picture2:　</p>
  </div>
  <div class="picture-selected", id="picture3-select">
    <p>picture3:　</p>
  </div>
  <div class="picture-selected", id="picture4-select">
    <p>picture4:　</p>
  </div>
  <div class="picture-selected", id="picture5-select">
    <p>picture5:　</p>
  </div>
  <div class="picture-selected", id="picture6-select">
    <p>picture6:　</p>
  </div>
  <div class="picture-selected", id="picture7-select">
    <p>picture7:　</p>
  </div>
  <div class="picture-selected", id="picture8-select">
    <p>picture8:　</p>
  </div>
  <div class="picture-selected", id="picture9-select">
    <p>picture9:　</p>
  </div>
  <div class="picture-selected", id="picture10-select">
    <p>picture10:　</p>
  </div>
  <div class="picture-selected", id="picture11-select">
    <p>picture11:　</p>
  </div>
  <div class="picture-selected", id="picture12-select">
    <p>picture12:　</p>
  </div>
</div>

app/views/calendars/new.html.erb
<div class="main">
  <p class="title">＜カレンダー作成画面＞</p>
  <% if flash[:notice] %>
    <p class="errors"><%= flash[:notice] %></p>
  <% end %>
  <div class="make-calendar">
    <% @images.each do |image| %>
      <div class="calendar-info">
        <div class="calendar-picture">
          <%= image_tag image.picture, class:"picture-box" %>
        </div>
        <div>
          <%= "シーズン：　#{image.season.name}" %><br />
          <% image.tags.each do |tag| %>
            <%= "##{tag.name}" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <%= render "monthselect"%>
</div>

app/views/calendars/show.html.erb
<div class="main">
  <p class="title">＜カレンダープレビュー＞　　all: 1000円（税抜き）</p>
    <%= render partial:"calendar" %>
  <div class="purchase">
    <%= link_to "購入へ", new_calendar_order_path(@calendar), class:"imagecal-link" %>
  </div>
</div>

app/views/calendars/show_order.html.erb
<div class="main">
  <div class="calendar-top-content">
    <div>
      <p class="calendar-title"><%= "#{l @order.calendar.created_at, format: :long}の注文分" %></p>
    </div>
    <div class="mailing">
      <p>郵送先：</p>
      <div class="mailing-info">
        <%= "〒#{@order.mailing.postal_code}　" %>
        <%= @order.mailing.prefecture.name %>
        <%= @order.mailing.city %>
        <%= @order.mailing.address %>
        <%= @order.mailing.building  if @order.mailing.building.present?%><br />
        <%= "#{current_user.firstname}　#{current_user.lastname}様宛" %>
        <%= "　　TEL:#{@order.mailing.tel}" %>
      </div>
    </div>
  </div>
  <%= render partial:"calendar" %>
</div>