config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  root to: "images#index"
  resources :images, only: [:index, :new, :create, :show, :destroy] do
   collection do
     get 'search'
     get 'notice'
   end
  end
  resources :users, only: [:new, :show, :index]
  get '/ordering' => 'users#ordering'
  resources :carts, only:[:show, :destroy]
  post '/add_item' => 'carts#add_item'
  resources :line_items, only: :destroy
  resources :calendars, only: [:new, :create, :show] do
    member do 
      get'show_order'
    end
    resources :orders, only: [:new, :create]
  end
end

app/models/image.rb
class Image < ApplicationRecord

  has_one_attached :picture

  belongs_to :user
  has_many :image_tag_relations, dependent: :destroy
  has_many :tags, through: :image_tag_relations, dependent: :destroy
  has_many :line_items, dependent: :destroy
  has_many :carts, through: :line_items, dependent: :destroy
  has_many :image_calendars
  has_many :calendars, through: :image_calendars

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :season

  def self.show_jan

    @images_jan = Image.where(season_id: 2 )
  end

  def self.show_feb
    @images_feb = Image.where(season_id: 3 )
  end

  def self.show_mar
    @images_mar = Image.where(season_id: 4 )
  end

  def self.show_apr
    @images_apr = Image.where(season_id: 5 )
  end

  def self.show_may
    @images_may = Image.where(season_id: 6 )
  end

  def self.show_jun
    @images_jun = Image.where(season_id: 7 )
  end

  def self.show_jul
    @images_jul = Image.where(season_id: 8 )
  end

  def self.show_aug
    @images_aug = Image.where(season_id: 9 )
  end

  def self.show_sep
    @images_sep = Image.where(season_id: 10 )
  end

  def self.show_oct
    @images_oct = Image.where(season_id:11)
  end

  def self.show_nov
    @images_nov = Image.where(season_id: 12 )
  end

  def self.show_dec
    @images_dec = Image.where(season_id: 13)
  end
  
  def self.show_spr

    @images_spr = Image.where(season_id: 14 )
  end

  def self.show_sum
    @images_sum = Image.where(season_id: 15 )
  end

  def self.show_aut
    @images_aut = Image.where(season_id: 16 )
  end

  def self.show_win
    @images_win = Image.where(season_id: 17 )
  end

  def self.show_all
    @images_all = Image.where(season_id: 18 )
  end

  def self.show_etc
    @images_etc = Image.where(season_id: 19 )
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy, :notice]
  before_action :show_monthly, only: :index
  before_action :find_image, only: [:show, :destroy]

  def index
    @images = Image.includes(:user).order(created_at: :desc)
    @cart = Cart.find_by(id: session[:cart_id])
  end
  def new
    @image = ImageTag.new
  end

  def create
    @image = ImageTag.new(image_params)
    if @image.valid?
      @image.save
      @image.tags_save(@tag_list)
      return redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def destroy
    @image.destroy
    redirect_to root_path
  end

  def search
    @images = Tag.search(params[:keyword])
  end

  def notice
  end

  private
  def image_params
    @tag_list = params[:image_tag][:name].split(",")
    params.require(:image_tag).permit(:comment, :picture, :season_id).merge(user_id: current_user.id)
  end

  def show_monthly
    @images_jan = Image.show_jan
    @images_feb = Image.show_feb
    @images_mar = Image.show_mar
    @images_apr = Image.show_apr
    @images_may = Image.show_may
    @images_jun = Image.show_jun
    @images_jul = Image.show_jul
    @images_aug = Image.show_aug
    @images_sep = Image.show_sep
    @images_oct = Image.show_oct
    @images_nov = Image.show_nov
    @images_dec = Image.show_dec
    @images_spr = Image.show_spr
    @images_sum = Image.show_sum
    @images_aut = Image.show_aut
    @images_win = Image.show_win
    @images_all = Image.show_all
    @images_etc = Image.show_etc
  end

  def find_image
    @image = Image.find(params[:id])
  end
end

app/helpers/images_helper.rb
module ImagesHelper
  def current_favorite?(product, favorite)
    favorite.check_items.map{|i|i.image_id}.include?(image.id)
  end
end

app/views/images/_apr.html.erb
<% if @images_apr.present? %>
  <% @images_apr.each do |image|%>
      <div class="select-image">
      <div class="picture-box">
        <%= link_to (image_tag image.picture, class:"image-picture"), image_path(image.id) %>
      </div>
      <div class="image-data">
        <div class="top-data">
          <div class="image-user">
            <%= link_to (image_tag image.user.icon, class:"usericon"), user_path(image.user.id) %>
            <%= link_to image.user.nickname, user_path(image.user.id), class:"imagecal-link" %>
          </div>
          <div>
            <%= "シーズン：#{image.season.name}"%>
          </div>
        </div>
        <div class="bottom-data">
          <%if image.tags.present?%>
            <% image.tags.each do |tag|%>
              <%= "##{tag.name}" %>
            <% end%>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/images/_aut.html.erb
<% if @images_aut.present? %>
  <% @images_aut.each do |image|%>
      <div class="select-image">
      <div class="picture-box">
        <%= link_to (image_tag image.picture, class:"image-picture"), image_path(image.id) %>
      </div>
      <div class="image-data">
        <div class="top-data">
          <div class="image-user">
            <%= link_to (image_tag image.user.icon, class:"usericon"), user_path(image.user.id) %>
            <%= link_to image.user.nickname, user_path(image.user.id), class:"imagecal-link" %>
          </div>
          <div>
            <%= "シーズン：#{image.season.name}"%>
          </div>
        </div>
        <div class="bottom-data">
          <%if image.tags.present?%>
            <% image.tags.each do |tag|%>
              <%= "##{tag.name}" %>
            <% end%>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/images/_dec.html.erb
<% if @images_dec.present? %>
  <% @images_dec.each do |image|%>
      <div class="select-image">
      <div class="picture-box">
        <%= link_to (image_tag image.picture, class:"image-picture"), image_path(image.id) %>
      </div>
      <div class="image-data">
        <div class="top-data">
          <div class="image-user">
            <%= link_to (image_tag image.user.icon, class:"usericon"), user_path(image.user.id) %>
            <%= link_to image.user.nickname, user_path(image.user.id), class:"imagecal-link" %>
          </div>
          <div>
            <%= "シーズン：#{image.season.name}"%>
          </div>
        </div>
        <div class="bottom-data">
          <%if image.tags.present?%>
            <% image.tags.each do |tag|%>
              <%= "##{tag.name}" %>
            <% end%>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/images/_feb.html.erb
<% if @images_feb.present? %>
  <% @images_feb.each do |image|%>
      <div class="select-image">
      <div class="picture-box">
        <%= link_to (image_tag image.picture, class:"image-picture"), image_path(image.id) %>
      </div>
      <div class="image-data">
        <div class="top-data">
          <div class="image-user">
            <%= link_to (image_tag image.user.icon, class:"usericon"), user_path(image.user.id) %>
            <%= link_to image.user.nickname, user_path(image.user.id), class:"imagecal-link" %>
          </div>
          <div>
            <%= "シーズン：#{image.season.name}"%>
          </div>
        </div>
        <div class="bottom-data">
          <%if image.tags.present?%>
            <% image.tags.each do |tag|%>
              <%= "##{tag.name}" %>
            <% end%>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/images/_jul.html.erb
<% if @images_jul.present? %>
  <% @images_jul.each do |image|%>
      <div class="select-image">
      <div class="picture-box">
        <%= link_to (image_tag image.picture, class:"image-picture"), image_path(image.id) %>
      </div>
      <div class="image-data">
        <div class="top-data">
          <div class="image-user">
            <%= link_to (image_tag image.user.icon, class:"usericon"), user_path(image.user.id) %>
            <%= link_to image.user.nickname, user_path(image.user.id), class:"imagecal-link" %>
          </div>
          <div>
            <%= "シーズン：#{image.season.name}"%>
          </div>
        </div>
        <div class="bottom-data">
          <%if image.tags.present?%>
            <% image.tags.each do |tag|%>
              <%= "##{tag.name}" %>
            <% end%>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/images/_jun.html.erb
<% if @images_jun.present? %>
  <% @images_jun.each do |image|%>
      <div class="select-image">
      <div class="picture-box">
        <%= link_to (image_tag image.picture, class:"image-picture"), image_path(image.id) %>
      </div>
      <div class="image-data">
        <div class="top-data">
          <div class="image-user">
            <%= link_to (image_tag image.user.icon, class:"usericon"), user_path(image.user.id) %>
            <%= link_to image.user.nickname, user_path(image.user.id), class:"imagecal-link" %>
          </div>
          <div>
            <%= "シーズン：#{image.season.name}"%>
          </div>
        </div>
        <div class="bottom-data">
          <%if image.tags.present?%>
            <% image.tags.each do |tag|%>
              <%= "##{tag.name}" %>
            <% end%>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/images/_nov.html.erb
<% if @images_nov.present? %>
  <% @images_nov.each do |image|%>
      <div class="select-image">
      <div class="picture-box">
        <%= link_to (image_tag image.picture, class:"image-picture"), image_path(image.id) %>
      </div>
      <div class="image-data">
        <div class="top-data">
          <div class="image-user">
            <%= link_to (image_tag image.user.icon, class:"usericon"), user_path(image.user.id) %>
            <%= link_to image.user.nickname, user_path(image.user.id), class:"imagecal-link" %>
          </div>
          <div>
            <%= "シーズン：#{image.season.name}"%>
          </div>
        </div>
        <div class="bottom-data">
          <%if image.tags.present?%>
            <% image.tags.each do |tag|%>
              <%= "##{tag.name}" %>
            <% end%>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/images/_oct.html.erb
<% if @images_oct.present? %>
  <% @images_oct.each do |image|%>
      <div class="select-image">
      <div class="picture-box">
        <%= link_to (image_tag image.picture, class:"image-picture"), image_path(image.id) %>
      </div>
      <div class="image-data">
        <div class="top-data">
          <div class="image-user">
            <%= link_to (image_tag image.user.icon, class:"usericon"), user_path(image.user.id) %>
            <%= link_to image.user.nickname, user_path(image.user.id), class:"imagecal-link" %>
          </div>
          <div>
            <%= "シーズン：#{image.season.name}"%>
          </div>
        </div>
        <div class="bottom-data">
          <%if image.tags.present?%>
            <% image.tags.each do |tag|%>
              <%= "##{tag.name}" %>
            <% end%>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/images/_sep.html.erb
<% if @images_sep.present? %>
  <% @images_sep.each do |image|%>
      <div class="select-image">
      <div class="picture-box">
        <%= link_to (image_tag image.picture, class:"image-picture"), image_path(image.id) %>
      </div>
      <div class="image-data">
        <div class="top-data">
          <div class="image-user">
            <%= link_to (image_tag image.user.icon, class:"usericon"), user_path(image.user.id) %>
            <%= link_to image.user.nickname, user_path(image.user.id), class:"imagecal-link" %>
          </div>
          <div>
            <%= "シーズン：#{image.season.name}"%>
          </div>
        </div>
        <div class="bottom-data">
          <%if image.tags.present?%>
            <% image.tags.each do |tag|%>
              <%= "##{tag.name}" %>
            <% end%>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/images/_spr.html.erb
<% if @images_spr.present? %>
  <% @images_spr.each do |image|%>
      <div class="select-image">
      <div class="picture-box">
        <%= link_to (image_tag image.picture, class:"image-picture"), image_path(image.id) %>
      </div>
      <div class="image-data">
        <div class="top-data">
          <div class="image-user">
            <%= link_to (image_tag image.user.icon, class:"usericon"), user_path(image.user.id) %>
            <%= link_to image.user.nickname, user_path(image.user.id), class:"imagecal-link" %>
          </div>
          <div>
            <%= "シーズン：#{image.season.name}"%>
          </div>
        </div>
        <div class="bottom-data">
          <%if image.tags.present?%>
            <% image.tags.each do |tag|%>
              <%= "##{tag.name}" %>
            <% end%>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/images/_tab.html.erb
<div class="month-tabs">
  <input type="radio" name="tab_name" id="tab1" checked>
  <label class="tab_class" for="tab1">1月</label>
  <div class="content_class">
    <%= render partial:"jan"%>
  </div>
  <input type="radio" name="tab_name" id="tab2" >
  <label class="tab_class" for="tab2">2月</label>
  <div class="content_class">
    <%= render partial:"feb"%>
  </div>
  <input type="radio" name="tab_name" id="tab3" >
  <label class="tab_class" for="tab3">3月</label>
  <div class="content_class">
    <%= render partial:"mar"%>
  </div>
  <input type="radio" name="tab_name" id="tab4" >
  <label class="tab_class" for="tab4">4月</label>
  <div class="content_class">
    <%= render partial:"apr"%>
  </div>
  <input type="radio" name="tab_name" id="tab5" >
  <label class="tab_class" for="tab5">5月</label>
  <div class="content_class">
    <%= render partial:"may"%>
  </div>
  <input type="radio" name="tab_name" id="tab6" checked>
  <label class="tab_class" for="tab6">6月</label>
  <div class="content_class">
    <%= render partial:"jun"%>
  </div>
  <input type="radio" name="tab_name" id="tab7" >
  <label class="tab_class" for="tab7">7月</label>
  <div class="content_class">
    <%= render partial:"jul"%>
  </div>
  <input type="radio" name="tab_name" id="tab8" >
  <label class="tab_class" for="tab8">8月</label>
  <div class="content_class">
  <%= render partial:"aug"%>
  </div>
  <input type="radio" name="tab_name" id="tab9" >
  <label class="tab_class" for="tab9">9月</label>
  <div class="content_class">
    <%= render partial:"sep"%>
  </div>
  <input type="radio" name="tab_name" id="tab10" >
  <label class="tab_class" for="tab10">10月</label>
  <div class="content_class">
    <%= render partial:"oct"%>
  </div>
  <input type="radio" name="tab_name" id="tab11" checked>
  <label class="tab_class" for="tab11">11月</label>
  <div class="content_class">
    <%= render partial:"nov"%>
  </div>
  <input type="radio" name="tab_name" id="tab12" >
  <label class="tab_class" for="tab12">12月</label>
  <div class="content_class">
    <%= render partial:"dec"%>
  </div>
  <input type="radio" name="tab_name" id="tab13" checked>
  <label class="tab_class" for="tab13">春</label>
  <div class="content_class">
    <%= render partial:"spr"%>
  </div>
  <input type="radio" name="tab_name" id="tab14" >
  <label class="tab_class" for="tab14">夏</label>
  <div class="content_class">
    <%= render partial:"sum"%>
  </div>
  <input type="radio" name="tab_name" id="tab15" >
  <label class="tab_class" for="tab15">秋</label>
  <div class="content_class">
    <%= render partial:"aut"%>
  </div>
  <input type="radio" name="tab_name" id="tab16" >
  <label class="tab_class" for="tab16">冬</label>
  <div class="content_class">
    <%= render partial:"win"%>
  </div>
  <input type="radio" name="tab_name" id="tab17" >
  <label class="tab_class" for="tab17">通年</label>
  <div class="content_class">
    <%= render partial:"all"%>
  </div>
  <input type="radio" name="tab_name" id="tab18" checked>
  <label class="tab_class" for="tab18">その他</label>
  <div class="content_class">
    <%= render partial:"etc"%>
  </div>
</div>

app/views/images/index.html.erb
<div class="page">
  <div class= "main">
    <div class="app_info">
      <%= image_tag 'app-info-icon', class:"app-info-icon" %>
    </div>
    <div class="new-arrival">
      <div>
        <p class="image-index-title">＜新着順＞</p>
      </div>
      <div class="search-form">
        <%= form_with(url: search_images_path, local: true, method: :get) do |f| %>
          <%= f.text_field :keyword, placeholder: "タグ検索" %>
          <%= f.submit "検索", class:"tag-search-btn" %>
        <% end %>
      </div>
    </div>
    <%= render partial:"new_arrival" %>
    <div class="monthly">
      <p class="image-index-title">＜シーズン別＞</p>
      <%= render partial:"tab" %>
    </div>
    <% if user_signed_in? %>
      <div class="bottom-menu">
        <div class="image-post-link">
          <%= link_to (image_tag 'icon_post.png', class:"post-icon", alt:"icon-post"), new_image_path, class:"image_post"%>
            <p>投稿する</p>
        </div>
        <% unless @cart.nil? %>
          <div class="cart-inside">
            <%= link_to (image_tag 'icon_cart.png', class:"cart-icon", alt:"icon-cart"), cart_path(@cart.id) %>
            <p>カートを見る</p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/images/new.html.erb
<div class="main">
  <p class="post-title">＜投稿ページ＞</p>
    <div class="post-notice">
      <p>投稿をするときは『<%= link_to "投稿するときの注意点", notice_images_path, target: :_blank %>』を確認ください！</p>
    </div>
    <%= render partial:"form" %>
</div>

app/views/images/search.html.erb
<div class="page">
  <div class= "main">
    <div class="app_info">
      <%= image_tag 'app-info-icon', class:"app-info-icon" %>
    </div>
    <div class="new-arrival">
      <div>
        <p class="image-index-title">＜新着順＞</p>
      </div>
      <div class="search-form">
        <%= form_with(url: search_images_path, local: true, method: :get) do |f| %>
          <%= f.text_field :keyword, placeholder: "タグ検索" %>
          <%= f.submit "検索", class:"tag-search-btn" %>
        <% end %>
      </div>
    </div>
    <%= render partial:"new_arrival" %>
    <div class="monthly">
      <p class="image-index-title">＜シーズン別＞</p>
      <%= render partial:"tab" %>
    </div>
    <% if user_signed_in? %>
      <div class="bottom-menu">
        <div class="image-post-link">
          <%= link_to (image_tag 'icon_post.png', class:"post-icon", alt:"icon-post"), new_image_path, class:"image_post"%>
            <p>投稿する</p>
        </div>
        <% unless @cart.nil? %>
          <div class="cart-inside">
            <%= link_to (image_tag 'icon_cart.png', class:"cart-icon"), cart_path(@cart.id) %>
            <p>カートを見る</p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>