config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  root to: "images#index"
  resources :images, only: [:index, :new, :create, :show, :destroy] do
   collection do
     get 'search'
     get 'notice'
   end
  end
  resources :users, only: [:new, :show, :index]
  get '/ordering' => 'users#ordering'
  resources :carts, only:[:show, :destroy]
  post '/add_item' => 'carts#add_item'
  resources :line_items, only: :destroy
  resources :calendars, only: [:new, :create, :show] do
    member do 
      get'show_order'
    end
    resources :orders, only: [:new, :create]
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imagecal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class= "header">
      <%= link_to "ImageCal", root_path, class:"logo" %>
      <div class="user_button">
        <% if user_signed_in? %>
          <div class="username_btn">
            <%= link_to current_user.nickname, user_path(current_user.id) %>
          </div>
          <div class="menu">
            <%= image_tag 'icon_menu.png', size: "55x55", id: "menutab", alt:"メニューリスト"%>
          </div>
          <ul class="menu-list", id="menu-list"> 
            <div class="logout">
              <li class="menu-selct"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            </div>
            <div class="mypage">
              <li class="menu-select"><%= link_to "設定", users_path %></li>
            </div>
            <div class="user-order">
              <li class="menuselect"><%= link_to "購入履歴", ordering_path, method: :get %></li>
            </div>
          </ul>
        <% else %>
          <div class="user_btn">
            <%= link_to "新規登録", new_user_path%>
          </div>
          <div class="user_btn">
            <%= link_to "ログイン", new_user_session_path %>
          </div>
        <% end %> 
      </div>
    </div>
    <%= yield %>
    <div class= "footer"></div>
  </body>
</html>